"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import {
  Layers, GitCommit, Check, X, Pencil, Save, RotateCcw, History, AlertTriangle
} from "lucide-react";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle
} from "@/components/ui/dialog";
import { toast } from "sonner";

// ===== Types =====

interface PromptVersion {
  version: string;       // e.g., "v3"
  content: string;
  createdAt: string;     // YYYY-MM-DD
  active: boolean;
  note?: string;         // optional change note ("tightened anti-leakage")
}

interface Prompt {
  id: string;
  name: string;          // filename
  oneLine: string;       // 1-line "what it does"
  notes: string;         // longer rationale
  versions: PromptVersion[];
}

// ===== Seed prompts =====

const SEED_PROMPTS: Prompt[] = [
  // ========== Generation ==========
  {
    id: "interview-generator",
    name: "interview-generator.md",
    oneLine: "Takes concepts + difficulty + domain and outputs the complete interview problem bundle (statement, rubric, hints, follow-ups, solutions) in one shot.",
    notes: "Single prompt that returns the whole bundle. Easier to debug, version, and reason about than chaining 4 sub-prompts.",
    versions: [
      {
        version: "v1",
        active: false,
        createdAt: "2026-03-04",
        note: "Initial — only generated problem statement; rubric/hints/follow-ups were chained separately.",
        content: `# Interview Problem Generator (v1)

Generate a DSA interview problem.

Inputs: primary_concepts, secondary_concepts, difficulty, domain.

Output: { title, statement, example_input, example_output, constraints }.

Rules:
- Real-world framing
- Brute force should TLE
- Don't copy LeetCode top 150`,
      },
      {
        version: "v2",
        active: false,
        createdAt: "2026-04-10",
        note: "Added gold-set grounding. Still chained — rubric/hints/follow-ups were separate prompts.",
        content: `# Interview Problem Generator (v2)

Generate problem statement grounded in interview gold set few-shot examples.

Inputs: primary_concepts, secondary_concepts, must_not_require, difficulty, domain, gold_examples.

Output: { title, statement, input_format, output_format, example_input, example_output, constraints }.

(Rubric, hints, and follow-ups generated by separate downstream prompts.)`,
      },
      {
        version: "v3",
        active: true,
        createdAt: "2026-05-14",
        note: "Consolidated — single prompt now outputs the full bundle (statement + rubric + hints + follow-ups + solutions). Eliminated the 3 chained sub-prompts (rubric-generator, hint-ladder-generator, followup-generator).",
        content: `# Interview Problem Generator

You are generating a complete DSA **interview problem bundle**. Your single output must support a 30-minute live interview with back-and-forth dialogue — including the problem itself, an evaluator rubric, a hint ladder, follow-up questions, and reference solutions.

## Inputs
- primary_concepts: list of concepts being assessed
- secondary_concepts: concepts that may appear incidentally
- must_not_require: concepts the candidate should NOT need
- difficulty: easy / medium / hard
- problem_type: written_coding | written_coding_interview
- time_budget_min: target time for a strong candidate
- domain: real-world framing (e-commerce, fintech, social, etc.)
- gold_examples: 3–5 calibrated interview problems with similar concept profile

## Output schema (one JSON object, all fields required)
\`\`\`json
{
  "title": "string",
  "statement": "string (200-400 words)",
  "input_format": "string",
  "output_format": "string",
  "example_input": "string",
  "example_output": "string",
  "constraints": ["string"],
  "rubric": [
    {
      "axis": "string (under 30 chars)",
      "band1": "observable behavior — weak candidate",
      "band3": "observable behavior — baseline candidate",
      "band5": "observable behavior — strong candidate"
    }
  ],
  "hints": [
    { "level": 1, "hint": "conceptual nudge", "reveals": "string" },
    { "level": 2, "hint": "strategic nudge", "reveals": "string" },
    { "level": 3, "hint": "near-implementation", "reveals": "string" }
  ],
  "follow_ups": [
    {
      "question": "string",
      "new_insight_required": "string",
      "category": "streaming | distributed | online | bounded-memory | adversarial-input"
    }
  ],
  "solutions": [
    {
      "level": "brute | intermediate | optimal",
      "complexity_time": "string",
      "complexity_space": "string",
      "code": "string",
      "insight": "string"
    }
  ],
  "edge_cases": ["string"],
  "red_flags": ["string (common wrong approaches)"]
}
\`\`\`

## Hard constraints on the PROBLEM STATEMENT

1. **Leave 2–3 productive ambiguities** in the statement. A strong candidate should want to ask clarifying questions before coding. Do NOT over-specify.

2. **Real-world framing must do work.** If you can swap to "given an array of ints" without losing meaning, the framing is cosmetic. Reject and regenerate.

3. **Constraints force the optimal.** Set input bounds so a brute force times out.

4. **No pedagogical scaffolding.** Do NOT add hints, approach suggestions, or "you may use a hashmap" in the statement.

## Hard constraints on the RUBRIC

5. **Maximum 4 axes.** Beyond 4, raters disagree on which axis to use.
6. **Each band describes OBSERVABLE behavior**, not an outcome.
7. **Cover 3 behavior types**: at least one thinking axis, one communication axis, one rigor axis.

## Hard constraints on the HINT LADDER

8. **Exactly 3 hints, monotonically escalating.** H1 = conceptual, H2 = strategic, H3 = near-implementation.
9. **H3 must not be solvable trivially in under 2 min from H3 alone.** Pull back if it gives away the answer.

## Hard constraints on FOLLOW-UPS

10. **2–3 follow-ups, each requiring a NEW insight** — not just "make N bigger" or "K is larger".
11. **Each follow-up must map to a real engineering scenario** (streaming, distributed, bounded memory, etc.).

## Hard constraints on SOLUTIONS

12. **At least 2 solution tiers** (brute + optimal). 3 tiers preferred (brute + intermediate + optimal).
13. **Each solution tier must be a genuinely different approach**, not a micro-optimization of the previous.

## Anti-leakage

Before returning, check: is this problem (or a near-rename) on LeetCode top 150, NeetCode 150, or Striver A2Z? If yes, reject. Generate a variant that composes concepts in a way not present there.`,
      },
    ],
  },
  // ========== Eval judges ==========
  {
    id: "eval-clarifying-questions",
    name: "eval-clarifying-questions.md",
    oneLine: "Eval #1 — scores whether the problem statement leaves room for 2–3 productive clarifying questions before coding.",
    notes: "Judge prompt for the 'Problem statement should not have straightforward instructions' eval. Simulates an AI candidate reading the problem and counts good questions raised.",
    versions: [
      {
        version: "v1",
        active: true,
        createdAt: "2026-05-14",
        note: "Initial.",
        content: `# Eval Judge — Clarifying Questions

You are evaluating whether an interview problem statement is appropriately under-specified — i.e., it should prompt 2–3 sensible clarifying questions from a candidate before they start coding. Fully spelled-out statements behave like practice problems and provide no signal on a candidate's clarification instinct.

## Input
- problem_statement: the full text of the generated problem
- domain: the real-world framing used

## Process

1. **Simulate candidate behavior.** Imagine a strong candidate reading this problem for the first time. Before they write any code, what would they reasonably want to ask the interviewer?

2. **Enumerate clarifying questions.** List every question that is:
   - **Sensible**: a real candidate at SDE-level would ask this
   - **Not pedantic**: ignore questions like "are integers 32-bit?" unless the problem actually depends on it
   - **About the problem, not the format**: ignore "is this Python or Java?"

3. **Filter for ambiguity that matters.** A clarifying question is "productive" only if the answer changes what the candidate codes. Cosmetic questions don't count.

## Output schema
\`\`\`json
{
  "score": 1-5,
  "productive_questions_count": 0,
  "questions": [
    { "question": "string", "is_productive": true, "why_it_matters": "string" }
  ],
  "reasoning": "string (2-3 sentences)"
}
\`\`\`

## Scoring rubric

- **0 productive questions** → 1/5. Statement is fully spelled out. Practice problem in disguise.
- **1 productive question** → 2/5. A little too clean — most candidates would just start coding.
- **2–3 productive questions** → 5/5. Ideal. Statement invites dialogue.
- **4–5 productive questions** → 3/5. Borderline ambiguous. Some risk candidates feel lost rather than curious.
- **6+ productive questions** → 1/5. Statement is too vague — candidates can't tell what to build.`,
      },
    ],
  },
  {
    id: "eval-multiple-solutions",
    name: "eval-multiple-solutions.md",
    oneLine: "Eval #2 — counts how many genuinely different working solutions exist (across complexity tiers or with real trade-offs).",
    notes: "Judge prompt for the 'Has multiple solution approaches' eval. Enumerates working solutions and verifies each is meaningfully different.",
    versions: [
      {
        version: "v1",
        active: true,
        createdAt: "2026-05-14",
        note: "Initial.",
        content: `# Eval Judge — Multiple Solution Approaches

You are evaluating whether an interview problem supports a slow-then-fast ladder OR multiple parallel solutions with different trade-offs. Problems with only one viable solution turn into pass/fail and give partial-credit candidates nothing to show.

## Input
- problem_statement
- reference_solutions: list of solutions provided by the generator with code, time complexity, and space complexity

## Process

1. **Enumerate all reasonable working solutions** to this problem. Include the reference solutions plus any others you can construct.

2. **Classify each solution** by its algorithmic structure:
   - What is the core idea? (e.g., "nested scan", "sorted + two-pointer", "deque sliding window")
   - What data structure does it rely on?
   - What is its time and space complexity?

3. **Check pairwise for distinctness.** Two solutions are "the same" if one is a micro-optimization of the other (e.g., adding early termination). They are "genuinely different" if the core idea or primary data structure changes.

## Output schema
\`\`\`json
{
  "score": 1-5,
  "distinct_solutions_count": 0,
  "solutions": [
    {
      "summary": "string (one line)",
      "core_idea": "string",
      "data_structure": "string",
      "time_complexity": "string",
      "space_complexity": "string",
      "distinct_from_others": true
    }
  ],
  "reasoning": "string (2-3 sentences)"
}
\`\`\`

## Scoring rubric

- **1 distinct solution** → 1/5. Either you see the trick or you fail. No partial credit.
- **2 distinct solutions** (e.g., slow + fast across complexity tiers) → 4/5. Good — candidates can climb.
- **3+ distinct solutions** (multiple tiers OR parallel approaches with trade-offs) → 5/5. Rich discussion surface.`,
      },
    ],
  },
  {
    id: "eval-novelty-vs-assignments",
    name: "eval-novelty-vs-assignments.md",
    oneLine: "Eval #3 — checks similarity vs. the DSA assignment library so candidates haven't already done this as homework.",
    notes: "Judge prompt for the 'Novelty: Does this problem exist in assignments?' eval. Compares against our own assignments, not the public internet.",
    versions: [
      {
        version: "v1",
        active: true,
        createdAt: "2026-05-14",
        note: "Initial. Scoped to DSA_ASSIGNMENTS only — public corpus leakage is handled inside the generator.",
        content: `# Eval Judge — Novelty vs. Assignments

You are evaluating whether a generated interview problem is sufficiently distinct from problems in our own DSA assignment library. If a candidate already did this as homework, the interview measures their memory, not their thinking.

## Input
- generated_problem: { title, statement, primary_concepts, secondary_concepts, reference_solution }
- assignment_library: all problems in DSA_ASSIGNMENTS

## Process

1. **Embed the generated problem.** Use problem statement + concept set + reference solution as the embedding input.

2. **Compute cosine similarity** against the embedding of every assignment in the library. Apply a concept-overlap boost: if primary concepts overlap, boost the similarity by 0.10 (capped at 1.0).

3. **Identify the closest match.** Pull the top-1 by similarity and the top-5 for context.

4. **Structural shape comparison** on the closest match: compare input-output types, constraint magnitudes, and expected complexity tier. If shape matches even with different framing, treat as duplicate.

## Output schema
\`\`\`json
{
  "score": 1-5,
  "max_similarity": 0.0,
  "closest_match": {
    "assignment_id": "string",
    "assignment_title": "string",
    "similarity_score": 0.0,
    "shared_concepts": ["string"],
    "structural_similarity": "string"
  },
  "top_5_matches": [
    { "assignment_id": "string", "title": "string", "similarity": 0.0 }
  ],
  "verdict": "novel | borderline | duplicate",
  "reasoning": "string (2-3 sentences)"
}
\`\`\`

## Scoring rubric

- **max_similarity < 0.30** → 5/5. Verdict: novel. Safe to ship.
- **0.30 ≤ max_similarity < 0.50** → 3/5. Verdict: borderline. Flag for human review. Suggest concept-arrangement changes.
- **max_similarity ≥ 0.50** → 1/5. Verdict: duplicate. Reject and regenerate.

## Why this is scoped to our assignment library

The internet corpus (LeetCode, GFG, Striver) is handled inside the interview-generator's anti-leakage rule. THIS eval is about our own platform's exposure — students at Scaler did these assignments. Even an internet-novel problem can be a duplicate of last week's homework.`,
      },
    ],
  },
  {
    id: "eval-followups-need-new-thinking",
    name: "eval-followups-need-new-thinking.md",
    oneLine: "Eval #4 — judges whether each follow-up question requires a new insight, not just a parameter rescaling.",
    notes: "Judge prompt for the 'Has follow-up questions that need different thinking' eval. Counts only follow-ups that need genuinely new reasoning.",
    versions: [
      {
        version: "v1",
        active: true,
        createdAt: "2026-05-14",
        note: "Initial.",
        content: `# Eval Judge — Follow-Ups Need New Thinking

You are evaluating whether the generated follow-up questions actually probe deeper, or whether they are trivial variants of the main problem. Good follow-ups require a new insight; bad ones just rescale parameters.

## Input
- main_problem: the original problem statement
- main_solution: the reference optimal solution
- follow_ups: list of generated follow-up questions with their declared new_insight_required and category

## Process

For each follow-up:

1. **Construct a solution** to the follow-up. What changes from the main solution?

2. **Classify the change:**
   - **New idea**: requires a different algorithm, data structure, or invariant (e.g., out-of-order events need a different invariant; bounded memory needs a different data structure)
   - **Rescaling**: same solution scaled up (e.g., "what if N = 10^9 instead of 10^5") — same code, just bigger inputs
   - **Parameter tweak**: solution structure unchanged, only a constant differs (e.g., "what if K is larger")

3. **Verify scenario grounding.** Each follow-up should have a real engineering scenario ("in production this happens because...") — not pure complexity theatre.

## Output schema
\`\`\`json
{
  "score": 1-5,
  "followups_needing_new_idea": 0,
  "followups_evaluated": [
    {
      "question": "string",
      "category_claimed": "string",
      "judge_classification": "new_idea | rescaling | parameter_tweak",
      "what_changes_in_solution": "string",
      "has_scenario_grounding": true
    }
  ],
  "reasoning": "string (2-3 sentences)"
}
\`\`\`

## Scoring rubric

- **0 follow-ups need a new idea** → 1/5. All trivial rescaling. Strong candidates have nothing to do.
- **1 follow-up needs a new idea** → 3/5. Some depth but borderline.
- **2 follow-ups need new ideas** → 4/5. Good.
- **3 follow-ups, each needing a different new idea** → 5/5. Strong candidates can be properly stretched.`,
      },
    ],
  },
  {
    id: "eval-hint-ladder-escalation",
    name: "eval-hint-ladder-escalation.md",
    oneLine: "Eval #5 — verifies that each hint reveals strictly more than the last (H1 → H2 → H3 escalates properly).",
    notes: "Judge prompt for the 'Hints get more specific as they go' eval. Reads the 3 hints in order and judges each gap.",
    versions: [
      {
        version: "v1",
        active: true,
        createdAt: "2026-05-14",
        note: "Initial.",
        content: `# Eval Judge — Hint Ladder Escalation

You are evaluating whether a 3-level hint ladder escalates properly. Each hint must reveal strictly more than the previous one without giving away the answer. Bad ladders either bunch the hints together (H2 and H3 are the same) or give away too much in H3.

## Input
- problem_statement
- optimal_solution
- hints: array of { level, hint, reveals }

## Process

1. **Read H1, H2, H3 in order.** For each hint, identify exactly what new information it adds compared to the previous hint(s).

2. **Check each gap:**
   - **H1 → H2 gap**: does H2 reveal strategically more (e.g., "use a queue") than H1's conceptual nudge ("think about state per user")?
   - **H2 → H3 gap**: does H3 reveal implementation-level detail (e.g., "deque per user, pop from front") beyond H2's strategic suggestion?
   - **Each gap must be meaningful**: if H2 and H3 essentially say the same thing, the ladder collapses to 2 effective hints.

3. **H3 saturation check.** Could a candidate who is otherwise stuck solve the problem in under 2 minutes given only H3? If yes, H3 has given away the answer.

4. **Hint count check.** There must be exactly 3 hints. Fewer = inadequate ladder. More = diluted.

## Output schema
\`\`\`json
{
  "score": 1-5,
  "hint_count": 3,
  "gaps": [
    {
      "from": "H1",
      "to": "H2",
      "new_info_added": "string",
      "is_meaningful_gap": true
    },
    {
      "from": "H2",
      "to": "H3",
      "new_info_added": "string",
      "is_meaningful_gap": true
    }
  ],
  "h3_saturates_solution": false,
  "reasoning": "string (2-3 sentences)"
}
\`\`\`

## Scoring rubric

- **Both gaps meaningful, H3 doesn't saturate, exactly 3 hints** → 5/5.
- **Both gaps meaningful but H3 gives too much away** → 3/5. Pull back H3.
- **One gap collapsed (H2 ≈ H3 or H1 ≈ H2)** → 2/5. Effectively a 2-hint ladder.
- **Both gaps collapsed OR fewer than 3 hints** → 1/5.`,
      },
    ],
  },
];

// ===== Local storage helpers =====

// v2 bumps the storage key so the old (chained-generator) saved prompts are discarded.
const STORAGE_KEY = "app:interview_prompts_v2";

function loadPrompts(): Prompt[] {
  if (typeof window === "undefined") return SEED_PROMPTS;
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return SEED_PROMPTS;
    return JSON.parse(raw) as Prompt[];
  } catch {
    return SEED_PROMPTS;
  }
}

function savePrompts(prompts: Prompt[]) {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(prompts));
  } catch {
    // ignore
  }
}

function nextVersion(versions: PromptVersion[]): string {
  const max = versions.reduce((acc, v) => {
    const n = parseInt(v.version.replace(/[^\d]/g, ""), 10);
    return isNaN(n) ? acc : Math.max(acc, n);
  }, 0);
  return `v${max + 1}`;
}

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

// ===== Components =====

interface PromptDialogProps {
  prompt: Prompt | null;
  onClose: () => void;
  onSaveNewVersion: (promptId: string, content: string, note: string) => void;
  onRollback: (promptId: string, version: string) => void;
}

function PromptDialog({ prompt, onClose, onSaveNewVersion, onRollback }: PromptDialogProps) {
  const [mode, setMode] = useState<"view" | "edit">("view");
  const [editContent, setEditContent] = useState("");
  const [editNote, setEditNote] = useState("");
  const [showHistory, setShowHistory] = useState(false);

  // Reset mode whenever a different prompt opens
  useEffect(() => {
    setMode("view");
    setEditContent(prompt ? prompt.versions.find(v => v.active)?.content || "" : "");
    setEditNote("");
    setShowHistory(false);
  }, [prompt?.id]);

  if (!prompt) return null;
  const active = prompt.versions.find(v => v.active);
  const previousVersions = prompt.versions.filter(v => !v.active).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  const proposedVersion = nextVersion(prompt.versions);

  function handleSave() {
    if (!editContent.trim()) {
      toast.error("Prompt content cannot be empty");
      return;
    }
    if (editContent === active?.content) {
      toast.info("No changes to save");
      return;
    }
    onSaveNewVersion(prompt!.id, editContent, editNote || "Manual edit");
    setMode("view");
    toast.success(`${proposedVersion} saved and promoted to production`);
  }

  function handleRollback(version: string) {
    onRollback(prompt!.id, version);
    toast.success(`Rolled back to ${version} — now active`);
  }

  return (
    <Dialog open={!!prompt} onOpenChange={open => !open && onClose()}>
      <DialogContent className="max-w-4xl max-h-[88vh] overflow-hidden flex flex-col">
        <DialogHeader>
          <div className="flex items-center gap-2 flex-wrap">
            <Layers size={14} className="text-violet-400" />
            <DialogTitle className="font-mono text-sm">{prompt.name}</DialogTitle>
            <span className="text-[10px] bg-violet-900/30 border border-violet-800/40 text-violet-300 rounded px-1.5 py-0.5">{active?.version || "—"}</span>
            <span className="text-[10px] bg-emerald-900/30 border border-emerald-800/40 text-emerald-400 rounded px-1.5 py-0.5 flex items-center gap-1">
              <Check size={9} />
              production
            </span>
            <span className="text-xs text-neutral-500 ml-auto flex items-center gap-1">
              <GitCommit size={11} />
              {active?.createdAt}
            </span>
          </div>
          <p className="text-xs text-neutral-300 mt-1.5">{prompt.oneLine}</p>
          <p className="text-[11px] text-neutral-500 italic mt-0.5">{prompt.notes}</p>
        </DialogHeader>

        {/* Action bar */}
        <div className="flex items-center gap-2 mt-2 pb-2 border-b border-white/5">
          {mode === "view" ? (
            <>
              <button
                onClick={() => { setMode("edit"); setEditContent(active?.content || ""); }}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-violet-600 hover:bg-violet-500 text-white text-xs transition-colors"
              >
                <Pencil size={11} />
                Edit Prompt
              </button>
              <button
                onClick={() => setShowHistory(!showHistory)}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md border text-xs transition-colors ${
                  showHistory ? "border-violet-500/60 bg-violet-950/30 text-violet-300" : "border-white/10 text-neutral-400 hover:border-white/20 hover:text-neutral-200"
                }`}
              >
                <History size={11} />
                Version History ({prompt.versions.length})
              </button>
            </>
          ) : (
            <>
              <button
                onClick={handleSave}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-emerald-600 hover:bg-emerald-500 text-white text-xs transition-colors"
              >
                <Save size={11} />
                Save as {proposedVersion} & Promote to Production
              </button>
              <button
                onClick={() => { setMode("view"); setEditContent(active?.content || ""); setEditNote(""); }}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-md border border-white/10 hover:border-white/20 text-neutral-300 text-xs transition-colors"
              >
                <X size={11} />
                Cancel
              </button>
              <p className="text-[11px] text-amber-400/80 ml-auto flex items-center gap-1.5">
                <AlertTriangle size={11} />
                Saving creates a new version and promotes it. Previous version stays in history.
              </p>
            </>
          )}
        </div>

        {/* Main content area */}
        <div className="flex-1 overflow-y-auto mt-3">
          {mode === "view" && !showHistory && (
            <div className="rounded-md border border-white/8 bg-neutral-950/60 p-4">
              <pre className="text-xs text-neutral-300 font-mono whitespace-pre-wrap leading-relaxed">{active?.content}</pre>
            </div>
          )}

          {mode === "edit" && (
            <div className="space-y-3">
              <div>
                <label className="text-xs text-neutral-400 mb-1.5 block">Change note (shown in version history)</label>
                <input
                  value={editNote}
                  onChange={e => setEditNote(e.target.value)}
                  placeholder="e.g. Tightened the anti-leakage clause; added must_not_require input"
                  className="w-full bg-neutral-800 border border-white/10 rounded px-3 py-2 text-xs text-neutral-200 outline-none focus:border-violet-500/60 placeholder:text-neutral-600"
                />
              </div>
              <div>
                <label className="text-xs text-neutral-400 mb-1.5 block">Prompt content</label>
                <textarea
                  value={editContent}
                  onChange={e => setEditContent(e.target.value)}
                  className="w-full bg-neutral-950/60 border border-white/10 rounded p-3 text-xs text-neutral-200 font-mono outline-none focus:border-violet-500/60 leading-relaxed"
                  rows={28}
                />
              </div>
            </div>
          )}

          {mode === "view" && showHistory && (
            <div className="space-y-3">
              <p className="text-xs text-neutral-500">Showing {previousVersions.length} previous version{previousVersions.length !== 1 ? "s" : ""}. Click "Roll back" to promote any version back to production.</p>
              {previousVersions.length === 0 && (
                <p className="text-sm text-neutral-600 italic">No previous versions yet.</p>
              )}
              {previousVersions.map(v => (
                <details key={v.version} className="rounded-md border border-white/8 bg-white/2 group">
                  <summary className="flex items-center gap-2 px-3 py-2.5 cursor-pointer hover:bg-white/3">
                    <span className="text-[10px] bg-neutral-800 border border-neutral-700 text-neutral-300 rounded px-1.5 py-0.5 font-mono">{v.version}</span>
                    <span className="text-xs text-neutral-500 flex items-center gap-1">
                      <GitCommit size={10} />
                      {v.createdAt}
                    </span>
                    <span className="text-xs text-neutral-400 italic">{v.note}</span>
                    <button
                      onClick={e => { e.preventDefault(); handleRollback(v.version); }}
                      className="ml-auto flex items-center gap-1 px-2 py-1 rounded bg-amber-900/30 hover:bg-amber-900/50 border border-amber-800/40 text-amber-300 text-[11px] transition-colors"
                    >
                      <RotateCcw size={10} />
                      Roll back to {v.version}
                    </button>
                  </summary>
                  <div className="px-3 pb-3">
                    <div className="rounded border border-white/5 bg-neutral-950/60 p-3 max-h-64 overflow-y-auto">
                      <pre className="text-[11px] text-neutral-400 font-mono whitespace-pre-wrap leading-relaxed">{v.content}</pre>
                    </div>
                  </div>
                </details>
              ))}
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}

function PromptCard({ prompt, onClick }: { prompt: Prompt; onClick: () => void }) {
  const active = prompt.versions.find(v => v.active);
  return (
    <button
      onClick={onClick}
      className="block w-full text-left rounded-lg border border-white/8 bg-white/2 p-4 hover:border-violet-500/40 hover:bg-violet-950/10 transition-colors"
    >
      <div className="flex items-start justify-between mb-1 gap-3">
        <div className="flex items-center gap-2 flex-wrap min-w-0">
          <Layers size={14} className="text-violet-400 shrink-0" />
          <p className="text-sm font-medium text-neutral-200 font-mono truncate">{prompt.name}</p>
          <span className="text-[10px] bg-violet-900/30 border border-violet-800/40 text-violet-300 rounded px-1.5 py-0.5">{active?.version}</span>
          <span className="text-[10px] bg-emerald-900/30 border border-emerald-800/40 text-emerald-400 rounded px-1.5 py-0.5 flex items-center gap-1">
            <Check size={9} />
            production
          </span>
          {prompt.versions.length > 1 && (
            <span className="text-[10px] bg-neutral-800 border border-neutral-700 text-neutral-400 rounded px-1.5 py-0.5 flex items-center gap-1">
              <History size={9} />
              {prompt.versions.length} versions
            </span>
          )}
        </div>
        <span className="text-xs text-neutral-500 flex items-center gap-1 shrink-0">
          <GitCommit size={11} />
          {active?.createdAt}
        </span>
      </div>
      <p className="text-xs text-neutral-300 ml-6 mt-0.5">{prompt.oneLine}</p>
      <p className="text-[11px] text-neutral-500 italic ml-6 mt-1">{prompt.notes}</p>
      <p className="text-[11px] text-violet-400/70 ml-6 mt-1.5">Click to view, edit, or roll back →</p>
    </button>
  );
}

export default function InterviewPromptsPage() {
  const [prompts, setPrompts] = useState<Prompt[]>(SEED_PROMPTS);
  const [openId, setOpenId] = useState<string | null>(null);

  const generationPrompts = prompts.filter(p => !p.id.startsWith("eval-"));
  const evalPrompts = prompts.filter(p => p.id.startsWith("eval-"));

  // Hydrate from localStorage on mount
  useEffect(() => {
    setPrompts(loadPrompts());
  }, []);

  function updatePrompts(next: Prompt[]) {
    setPrompts(next);
    savePrompts(next);
  }

  function handleSaveNewVersion(promptId: string, content: string, note: string) {
    const next = prompts.map(p => {
      if (p.id !== promptId) return p;
      const newVersion: PromptVersion = {
        version: nextVersion(p.versions),
        content,
        createdAt: today(),
        active: true,
        note,
      };
      const versions = p.versions.map(v => ({ ...v, active: false }));
      return { ...p, versions: [...versions, newVersion] };
    });
    updatePrompts(next);
  }

  function handleRollback(promptId: string, version: string) {
    const next = prompts.map(p => {
      if (p.id !== promptId) return p;
      const versions = p.versions.map(v => ({ ...v, active: v.version === version }));
      return { ...p, versions };
    });
    updatePrompts(next);
  }

  const openPrompt = prompts.find(p => p.id === openId) || null;

  return (
    <div className="p-8 max-w-6xl mx-auto">
      <div className="mb-6">
        <div className="flex items-center gap-2 text-xs text-neutral-500 mb-2">
          <Link href="/categories/dsa" className="hover:text-neutral-300">DSA</Link>
          <span>/</span>
          <Link href="/categories/dsa/interview" className="hover:text-neutral-300">Interview</Link>
          <span>/</span>
          <span className="text-neutral-300">Prompts</span>
        </div>
        <h1 className="text-2xl font-semibold text-neutral-100">Interview Prompts</h1>
        <p className="text-sm text-neutral-400 mt-1">
          1 generator prompt + 5 eval judge prompts (one per Eval Judge dimension). Click any prompt to view, edit, promote a new version, or roll back.
        </p>
      </div>

      {/* Generation section */}
      <div className="mb-6">
        <p className="text-xs font-semibold text-violet-300 uppercase tracking-wider mb-2">Generation</p>
        <div className="space-y-2">
          {generationPrompts.map(p => <PromptCard key={p.id} prompt={p} onClick={() => setOpenId(p.id)} />)}
        </div>
      </div>

      {/* Eval judges section */}
      <div className="mb-6">
        <p className="text-xs font-semibold text-violet-300 uppercase tracking-wider mb-2">Eval Judges</p>
        <p className="text-[11px] text-neutral-500 mb-2">
          One judge prompt per eval dimension on the <Link href="/categories/dsa/interview/evals" className="text-violet-400 hover:text-violet-300 underline">Evals</Link> page.
        </p>
        <div className="space-y-2">
          {evalPrompts.map(p => <PromptCard key={p.id} prompt={p} onClick={() => setOpenId(p.id)} />)}
        </div>
      </div>

      <div className="mt-6 rounded-md bg-violet-950/20 border border-violet-800/30 p-3 text-xs text-violet-300/80">
        <p className="font-medium mb-1">How this is wired</p>
        <ul className="text-violet-400/60 leading-relaxed space-y-0.5 list-disc list-inside">
          <li><span className="text-violet-300">Generation:</span> the single generator prompt runs when you click "Generate" — it returns the full problem bundle (statement, rubric, hints, follow-ups, solutions) in one LLM call.</li>
          <li><span className="text-violet-300">Eval Judges:</span> each judge prompt runs when you click "Run Eval" on the Evals page — one judge call per dimension, scored 1–5 against the generated bundle.</li>
          <li><span className="text-violet-300">Edit</span> opens a prompt in a textarea. Save creates a new version and promotes it to production. <span className="text-violet-300">Roll back</span> in Version History makes any previous version production again.</li>
        </ul>
      </div>

      <PromptDialog
        prompt={openPrompt}
        onClose={() => setOpenId(null)}
        onSaveNewVersion={handleSaveNewVersion}
        onRollback={handleRollback}
      />
    </div>
  );
}
